#!/usr/bin/env python3
"""medbot.py — Telegram bot for medical study tools, powered by Claude Haiku.

Presents three buttons — Lecture Notes, Quiz, Clinical Case — then asks for a
topic and replies with content generated by the Claude API. Reuses the prompt
and parsing logic from medteach.py, medquiz.py, and medcase.py.

Uses the raw HTTP API via `requests` (no `anthropic` package) and the Telegram
Bot API long-polling method (getUpdates). Tuned for minimum token usage.

Setup:
    pip install requests
    export ANTHROPIC_API_KEY="sk-ant-..."

Run:
    python medbot.py
"""

import html
import os
import sqlite3
import sys
import time
from datetime import date

import requests

# Reuse the existing study-tool logic (prompts + quiz parser).
from medteach import SYSTEM_PROMPT as TEACH_SYSTEM
from medquiz import SYSTEM_PROMPT as QUIZ_SYSTEM, parse_questions, OPTION_KEYS
from medcase import SYSTEM_PROMPT as CASE_SYSTEM

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_API = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}"

ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"
MODEL = "claude-haiku-4-5"

# Button labels and the mode each one selects.
BTN_NOTES = "🗒 Lecture Notes"
BTN_QUIZ  = "❓ Quiz"
BTN_CASE  = "🩺 Clinical Case"

MODES = {BTN_NOTES: "notes", BTN_QUIZ: "quiz", BTN_CASE: "case"}

# Per-mode config: system prompt, max_tokens (kept low), and the user prompt.
# max_tokens are deliberately minimal to keep cost down.
MODE_CONFIG = {
    "notes": {
        "system": TEACH_SYSTEM,
        "max_tokens": 800,   # reduced from 1200
        "prompt": "Brief lecture notes and mnemonics for: {topic}",  # shorter prompt
    },
    "quiz": {
        "system": QUIZ_SYSTEM,
        "max_tokens": 1000,  # reduced from 1500
        "prompt": "5 MCQs on: {topic}",  # shorter prompt
    },
    "case": {
        "system": CASE_SYSTEM,
        "max_tokens": 600,   # reduced from 800
        "prompt": "Clinical case for: {topic}",  # shorter prompt
    },
}

# Per-chat selected mode, awaiting a topic.
pending_mode = {}

TELEGRAM_LIMIT = 4096

# ── Daily usage limit ──────────────────────────────────────────────────────────
MAX_DAILY_REQUESTS = 10  # max API calls per user per day


def _usage_count(user_id):
    """Return today's request count for the user (0 if none / stale)."""
    today = str(date.today())
    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT date, count FROM usage WHERE user_id = ?",
            (user_id,),
        ).fetchone()
    if not row or row[0] != today:
        return 0
    return row[1]


def check_limit(user_id):
    """Return True if user is within daily limit, False if exceeded.

    Increments the persisted daily count when within the limit.
    """
    today = str(date.today())
    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT date, count FROM usage WHERE user_id = ?",
            (user_id,),
        ).fetchone()
        count = row[1] if row and row[0] == today else 0
        if count >= MAX_DAILY_REQUESTS:
            return False
        conn.execute(
            """
            INSERT INTO usage (user_id, date, count)
            VALUES (?, ?, 1)
            ON CONFLICT(user_id) DO UPDATE SET date = excluded.date, count = ?
            """,
            (user_id, today, count + 1),
        )
        conn.commit()
    return True


def remaining(user_id):
    return max(0, MAX_DAILY_REQUESTS - _usage_count(user_id))
# ──────────────────────────────────────────────────────────────────────────────


# ── Premium subscriptions (SQLite) ──────────────────────────────────────────────
DB_PATH = os.path.expanduser("~/medbot.db")

# Telegram user_id allowed to grant/revoke premium (set in the environment).
ADMIN_ID = int(os.environ.get("ADMIN_ID", "0")) or None

PREMIUM_MESSAGE = (
    "⭐ PREMIUM ₹99/month\n"
    "Pay: razorpay.me/@debabrataroy4703\n"
    "WhatsApp: +919051074983"
)


def init_db():
    """Create the users table if it does not exist."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                user_id     INTEGER PRIMARY KEY,
                is_premium  INTEGER NOT NULL DEFAULT 0,
                expiry_date TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS usage (
                user_id INTEGER PRIMARY KEY,
                date    TEXT NOT NULL,
                count   INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        conn.commit()


def is_premium(user_id):
    """Return True if the user has an active (non-expired) premium plan."""
    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT is_premium, expiry_date FROM users WHERE user_id = ?",
            (user_id,),
        ).fetchone()

    if not row or not row[0]:
        return False

    expiry = row[1]
    # No expiry date means the plan never expires.
    if expiry and str(date.today()) > expiry:
        return False
    return True


def grant_premium(user_id, expiry_date=None):
    """Mark a user as premium, optionally with an expiry (YYYY-MM-DD)."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            INSERT INTO users (user_id, is_premium, expiry_date)
            VALUES (?, 1, ?)
            ON CONFLICT(user_id) DO UPDATE SET is_premium = 1, expiry_date = excluded.expiry_date
            """,
            (user_id, expiry_date),
        )
        conn.commit()


def revoke_premium(user_id):
    """Remove a user's premium status."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "UPDATE users SET is_premium = 0, expiry_date = NULL WHERE user_id = ?",
            (user_id,),
        )
        conn.commit()
# ──────────────────────────────────────────────────────────────────────────────


def claude_text(mode, topic, api_key):
    """Call Claude (non-streaming) and return the response text, or an error."""
    cfg = MODE_CONFIG[mode]
    headers = {
        "Content-Type": "application/json",
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
    }
    payload = {
        "model": MODEL,
        "max_tokens": cfg["max_tokens"],
        "system": cfg["system"],
        "messages": [
            {"role": "user", "content": cfg["prompt"].format(topic=topic)}
        ],
    }

    try:
        resp = requests.post(ANTHROPIC_URL, headers=headers, json=payload, timeout=120)
    except requests.RequestException as e:
        return None, f"Network error contacting Claude: {e}"

    if resp.status_code != 200:
        return None, f"Claude API error {resp.status_code}."

    data = resp.json()
    if data.get("stop_reason") == "refusal":
        return None, "The request was declined by the model's safety system."

    text = "".join(
        block.get("text", "")
        for block in data.get("content", [])
        if block.get("type") == "text"
    ).strip()

    if not text:
        return None, "The model returned an empty response."
    return text, None


def format_quiz(text):
    """Turn the quiz JSON into a readable message with an answer key."""
    questions = parse_questions(text)
    if not questions:
        return text  # fall back to raw output if parsing fails

    lines = []
    for i, q in enumerate(questions, 1):
        lines.append(f"Q{i}. {q['question']}")
        for key in OPTION_KEYS:
            lines.append(f"  {key}. {q['options'][key]}")
        lines.append("")
    lines.append("— Answers —")
    for i, q in enumerate(questions, 1):
        line = f"{i}. {q['answer']}"
        if q["explanation"]:
            line += f" — {q['explanation']}"
        lines.append(line)
    return "\n".join(lines)


def send_message(chat_id, text, with_keyboard=False):
    """Send a message, chunked to Telegram's length limit."""
    payload = {"chat_id": chat_id}
    if with_keyboard:
        payload["reply_markup"] = {
            "keyboard": [[BTN_NOTES], [BTN_QUIZ], [BTN_CASE]],
            "resize_keyboard": True,
        }

    # Split long content across multiple messages.
    chunks = [text[i:i + TELEGRAM_LIMIT] for i in range(0, len(text), TELEGRAM_LIMIT)] or [""]
    for idx, chunk in enumerate(chunks):
        body = dict(payload)
        body["text"] = chunk
        # Only attach the keyboard to the final chunk.
        if with_keyboard and idx != len(chunks) - 1:
            body.pop("reply_markup", None)
        try:
            requests.post(f"{TELEGRAM_API}/sendMessage", json=body, timeout=30)
        except requests.RequestException as e:
            print(f"Failed to send message: {e}", file=sys.stderr)


def handle_message(message, api_key):
    """Process one incoming Telegram message."""
    chat_id = message["chat"]["id"]
    user_id = message["from"]["id"] if "from" in message else chat_id
    text = (message.get("text") or "").strip()
    if not text:
        return

    if text in ("/start", "/help"):
        pending_mode.pop(chat_id, None)
        send_message(
            chat_id,
            f"👋 Welcome to MedTeach Bot!\n\nPick a study tool below, then send a topic.\n\n📊 Daily limit: {MAX_DAILY_REQUESTS} requests/day\n⭐ Unlimited with Premium — send /premium",
            with_keyboard=True,
        )
        return

    if text == "/premium":
        send_message(chat_id, PREMIUM_MESSAGE)
        return

    # Admin-only: /grant <user_id> [YYYY-MM-DD]   and   /revoke <user_id>
    if text.startswith(("/grant", "/revoke")):
        if user_id != ADMIN_ID:
            send_message(chat_id, "⛔ Not authorized.")
            return
        parts = text.split()
        if len(parts) < 2 or not parts[1].lstrip("-").isdigit():
            send_message(chat_id, "Usage: /grant <user_id> [YYYY-MM-DD]  •  /revoke <user_id>")
            return
        target = int(parts[1])
        if parts[0] == "/grant":
            expiry = parts[2] if len(parts) > 2 else None
            grant_premium(target, expiry)
            send_message(chat_id, f"✅ Premium granted to {target}" + (f" until {expiry}." if expiry else " (no expiry)."))
        else:
            revoke_premium(target)
            send_message(chat_id, f"✅ Premium revoked for {target}.")
        return

    # Show remaining uses
    if text == "/usage":
        if is_premium(user_id):
            send_message(chat_id, "⭐ Premium active — unlimited requests.")
        else:
            rem = remaining(user_id)
            send_message(chat_id, f"📊 You have {rem}/{MAX_DAILY_REQUESTS} requests remaining today.")
        return

    if text in MODES:
        pending_mode[chat_id] = MODES[text]
        send_message(chat_id, f"{text} selected. Now send me a topic.")
        return

    mode = pending_mode.get(chat_id)
    if not mode:
        send_message(
            chat_id,
            "Pick a tool first using the buttons below.",
            with_keyboard=True,
        )
        return

    premium = is_premium(user_id)

    # ── Check daily limit before calling Claude (premium = unlimited) ──
    if not premium and not check_limit(user_id):
        send_message(
            chat_id,
            f"⚠️ Daily limit reached ({MAX_DAILY_REQUESTS} requests/day).\n"
            f"Resets at midnight. Come back tomorrow! 🌙\n\n"
            f"⭐ Want unlimited? Send /premium",
            with_keyboard=True,
        )
        return

    if premium:
        send_message(chat_id, f"⏳ Generating… (topic: {text})\n[⭐ Premium — unlimited]")
    else:
        rem = remaining(user_id)
        send_message(chat_id, f"⏳ Generating… (topic: {text})\n[{rem} requests left today]")
    result, err = claude_text(mode, text, api_key)
    if err:
        send_message(chat_id, err, with_keyboard=True)
        return

    if mode == "quiz":
        result = format_quiz(result)

    # Keep the chosen mode active so the user can send another topic.
    send_message(chat_id, result, with_keyboard=True)


def main():
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("Error: set the ANTHROPIC_API_KEY environment variable first.")

    init_db()

    print("MedBot is running (polling). Press Ctrl+C to stop.")
    offset = None

    while True:
        try:
            params = {"timeout": 30}
            if offset is not None:
                params["offset"] = offset
            resp = requests.get(
                f"{TELEGRAM_API}/getUpdates", params=params, timeout=40
            )
            updates = resp.json().get("result", [])
        except requests.RequestException as e:
            print(f"Polling error: {e}", file=sys.stderr)
            time.sleep(5)
            continue
        except KeyboardInterrupt:
            sys.exit("\nStopped.")

        for update in updates:
            offset = update["update_id"] + 1

            message = update.get("message") or update.get("edited_message")
            if message:
                try:
                    handle_message(message, api_key)
                except Exception as e:  # never let one bad update kill the bot
                    print(f"Error handling update: {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
